"""List of API endpoints PRAW knows about."""

# flake8: noqa
# fmt: off
API_PATH = {
'answers':'answers',
'answer_id':'answers/{ids}',
'answer_accept':'answers/{id}/accept',
'answer_accept_undo':'answers/{id}/accept/undo',
'answer_comments':'answers/{ids}/comments',
'answer_delete':'answers/{id}/delete',
'answer_downvote':'answers/{id}/downvote',
'answer_downvote_undo':'answers/{id}/downvote/undo',
'answer_edit':'answers/{id}/edit',
'answer_flag_options':'answers/{id}/flags/options',
'answer_flag_add':'answers/{id}/flags/add',
'answer_questions':'answers/{ids}/questions',
'answer_upvote':'answers/{id}/upvote',
'answer_upvote_undo':'answers/{id}/upvote/undo',
'answer_recommend':'answers/{id}/recommend',
'answer_recommend_undo':'answers/{id}/recommend/undo',
'answer_suggested_edit_add':'answers/{id}/suggested-edit/add',

'articles':'articles',
'article_id':'articles/{ids}',
'article_linked':'articles/{ids}/linked',
'article_delete':'articles/{id}/delete',
'article_edit':'articles/{id}/edit',
'article_add':'articles/add',

'badges':'badges',
'badge_id':'badges/{ids}',
'badge_name':'badges/name',
'badge_recipients':'badges/recipients',
'badge_id_recipients':'badges/{ids}/recipients',
'badge_tags':'badges/tags',

'collective':'collectives',
'collective_slugs':'collectives/{slugs}',
'collective_question':'collectives/{slugs}/question',
'collective_answers':'collectives/{slugs}/answers',
'collective_tags':'collectives/{slugs}/tags',
'collective_users':'collectives/{slugs}/users',
'collective_reports':'collectives/{slugs}/reports',
'collective_reports_add':'collectives/{slugs}/reports/add',

'comments':'comments',
'comment_id':'comments/{ids}',
'comment_delete':'comments/{id}/delete',
'comment_edit':'comments/{id}/edit',
'comment_flags_add':'comments/{id}/flags/add',
'comment_flags_options':'comments/{id}/flags/options',
'comment_upvote':'comments/{id}/upvote',
'comment_upvote_undo':'comments/{id}/upvote/undo',

'events':'events',

'info':'info',

'posts':'posts',
'post_id':'posts/{ids}',
'post_comments':'posts/{ids}/comments',
'post_comments_add':'posts/{id}/comments/add',
'post_comments_render':'posts/{id}/comments/render',
'post_revisions':'posts/{ids}/revisions',
'post_suggested_edits':'posts/{ids}/suggested-edits',

'questions':'questions',
'question_id':'questions/{ids}',
'question_answers':'questions/{ids}/answers',
'question_answers_add':'questions/{id}/answers/add',
'question_answers_render':'questions/{id}/answers/render',
'question_close_options':'questions/{id}/close/options',
'question_comments':'questions/{ids}/comments',
'question_delete':'questions/{id}/delete',
'question_downvote':'questions/{id}/downvote',
'question_downvote_undo':'questions/{id}/downvote/undo',
'question_edit':'questions/{id}/edit',
'question_favorite':'questions/{id}/favorite',
'question_favorite_undo':'questions/{id}/favorite/undo',
'question_flags_add':'questions/{id}/flags/add',
'question_flags_options':'questions/{id}/flags/options',
'question_linked':'questions/{ids}/linked',
'question_related':'questions/{ids}/related',
'question_suggested_edits_add':'questions/{id}/suggested-edit/add',
'question_timeline':'questions/{ids}/timeline',
'question_upvote':'questions/{id}/upvote',
'question_upvote_undo':'questions/{id}/upvote/undo',
'questions_add':'questions/add',
'questions_featured':'questions/featured',
'questions_no_answers':'questions/no-answers',
'questions_render':'questions/render',
'questions_unanswered':'questions/unanswered',
'questions_unanswered_my_tags':'questions/unanswered/my-tags',

'revision':'revisions/{ids}',

'search':'search',
'search_advanced':'search/advanced',
'search_excerpts':'search/excerpts',
'similar':'similar',

'suggested-edit':'suggested-edits',
'suggested-edit_id':'suggested-edits/{ids}',

'tags':'tags',
'tag_tags_info':'tags/{tags}/info',
'tags_moderator_only':'tags/moderator-only',
'tags_required':'tags/required',
'tags_synonyms':'tags/synonyms',
'tag_tags_fag':'tags/{tags}/faq',
'tag_tags_related':'tags/{tags}/related',
'tag_tags_synonyms':'tags/{tags}/synonyms',
'tags_tag_top_answerers_period':'tags/{tag}/top-answerers/{period}',
'tags_tag_top_askers_period':'tags/{tag}/top-askers/{period}',
'tag_tags_wiki':'tags/{tags}/wikis',

'users':'users',
'user_id':'users/{ids}',
'user_answers':'users/{ids}/answers',
'user_badges':'users/{ids}/badges',
'user_comments':'users/{ids}/comments',
'user_comments_to':'users/{ids}/comments/{toid}',
'user_favorites':'users/{ids}/favorites',
'user_mentioned':'users/{ids}/mentioned',
'user_network_activity':'users/{id}/network-activity',
'user_notifications':'users/{id}/notifications',
'user_notifications_unread':'users/{id}/notifications/unread',
'user_posts':'users/{ids}/posts',
'user_privileges':'users/{id}/privileges',
'user_questions':'users/{ids}/questions',
'user_questions_featured':'users/{ids}/questions/featured',
'user_questions_no_answers':'users/{ids}/questions/no-answers',
'user_questions_unaccepted':'users/{ids}/questions/unaccepted',
'user_questions_unanswered':'users/{ids}/questions/unanswered',
'user_reputation':'users/{ids}/reputation',
'user_reputation_history':'users/{ids}/reputation-history',
'user_reputation_history_full':'users/{id}/reputation-history/full',
'user_suggested_edits':'users/{ids}/suggested-edits',
'user_tags':'users/{ids}/tags',
'user_tags_top_answers':'users/{id}/tags/{tags}/top-answers',
'user_tags_top_questions':'users/{id}/tags/{tags}/top-questions',
'user_tag_tag_preferences':'users/{id}/tag-preferences',
'user_tag_preferences_edit':'users/{id}/tag-preferences/edit',
'user_timeline':'users/{ids}/timeline',
'user_top_answer_tags':'users/{id}/top-answer-tags',
'user_top_question_tags':'users/{id}/top-question-tags',
'user_top_tags':'users/{id}/top-tags',
'user_write_permissions':'users/{id}/write-permissions',
'users_moderators':'users/moderators',
'users_moderators_elected':'users/moderators/elected',
'user_inbox':'users/{id}/inbox',
'user_inbox_unread':'users/{id}/inbox/unread',
'user_achievements':'users/{id}/achievements',
'user_associated':'users/{ids}/associated',
'user_merges':'users/{ids}/merges',

    }
